2024-07-30 17:30:34,424:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=126.0.6478.183)
Stacktrace:
	GetHandleVerifier [0x00007FF6BCE7EEB2+31554]
	(No symbol) [0x00007FF6BCDF7EE9]
	(No symbol) [0x00007FF6BCCB872A]
	(No symbol) [0x00007FF6BCC8D995]
	(No symbol) [0x00007FF6BCD344D7]
	(No symbol) [0x00007FF6BCD4C051]
	(No symbol) [0x00007FF6BCD2CDD3]
	(No symbol) [0x00007FF6BCCFA33B]
	(No symbol) [0x00007FF6BCCFAED1]
	GetHandleVerifier [0x00007FF6BD188B2D+3217341]
	GetHandleVerifier [0x00007FF6BD1D5AF3+3532675]
	GetHandleVerifier [0x00007FF6BD1CB0F0+3489152]
	GetHandleVerifier [0x00007FF6BCF2E786+750614]
	(No symbol) [0x00007FF6BCE0376F]
	(No symbol) [0x00007FF6BCDFEB24]
	(No symbol) [0x00007FF6BCDFECB2]
	(No symbol) [0x00007FF6BCDEE17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 62, in run
    br.find_elements(By.CSS_SELECTOR, 'a[href*="https://www.google.com/maps/place/"]')[-1]
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1283, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=126.0.6478.183)
Stacktrace:
	GetHandleVerifier [0x00007FF6BCE7EEB2+31554]
	(No symbol) [0x00007FF6BCDF7EE9]
	(No symbol) [0x00007FF6BCCB872A]
	(No symbol) [0x00007FF6BCC8D995]
	(No symbol) [0x00007FF6BCD344D7]
	(No symbol) [0x00007FF6BCD4C051]
	(No symbol) [0x00007FF6BCD2CDD3]
	(No symbol) [0x00007FF6BCCFA33B]
	(No symbol) [0x00007FF6BCCFAED1]
	GetHandleVerifier [0x00007FF6BD188B2D+3217341]
	GetHandleVerifier [0x00007FF6BD1D5AF3+3532675]
	GetHandleVerifier [0x00007FF6BD1CB0F0+3489152]
	GetHandleVerifier [0x00007FF6BCF2E786+750614]
	(No symbol) [0x00007FF6BCE0376F]
	(No symbol) [0x00007FF6BCDFEB24]
	(No symbol) [0x00007FF6BCDFECB2]
	(No symbol) [0x00007FF6BCDEE17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-07-30 17:57:03,852:ERROR:gbm:Message: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=126.0.6478.183)
Stacktrace:
	GetHandleVerifier [0x00007FF6BCE7EEB2+31554]
	(No symbol) [0x00007FF6BCDF7EE9]
	(No symbol) [0x00007FF6BCCB872A]
	(No symbol) [0x00007FF6BCCA0FDD]
	(No symbol) [0x00007FF6BCCA0CE0]
	(No symbol) [0x00007FF6BCC9FC9B]
	(No symbol) [0x00007FF6BCCC630D]
	(No symbol) [0x00007FF6BCD4CCD5]
	(No symbol) [0x00007FF6BCD2CDD3]
	(No symbol) [0x00007FF6BCCFA33B]
	(No symbol) [0x00007FF6BCCFAED1]
	GetHandleVerifier [0x00007FF6BD188B2D+3217341]
	GetHandleVerifier [0x00007FF6BD1D5AF3+3532675]
	GetHandleVerifier [0x00007FF6BD1CB0F0+3489152]
	GetHandleVerifier [0x00007FF6BCF2E786+750614]
	(No symbol) [0x00007FF6BCE0376F]
	(No symbol) [0x00007FF6BCDFEB24]
	(No symbol) [0x00007FF6BCDFECB2]
	(No symbol) [0x00007FF6BCDEE17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 103, in run
    br.get(url)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=126.0.6478.183)
Stacktrace:
	GetHandleVerifier [0x00007FF6BCE7EEB2+31554]
	(No symbol) [0x00007FF6BCDF7EE9]
	(No symbol) [0x00007FF6BCCB872A]
	(No symbol) [0x00007FF6BCCA0FDD]
	(No symbol) [0x00007FF6BCCA0CE0]
	(No symbol) [0x00007FF6BCC9FC9B]
	(No symbol) [0x00007FF6BCCC630D]
	(No symbol) [0x00007FF6BCD4CCD5]
	(No symbol) [0x00007FF6BCD2CDD3]
	(No symbol) [0x00007FF6BCCFA33B]
	(No symbol) [0x00007FF6BCCFAED1]
	GetHandleVerifier [0x00007FF6BD188B2D+3217341]
	GetHandleVerifier [0x00007FF6BD1D5AF3+3532675]
	GetHandleVerifier [0x00007FF6BD1CB0F0+3489152]
	GetHandleVerifier [0x00007FF6BCF2E786+750614]
	(No symbol) [0x00007FF6BCE0376F]
	(No symbol) [0x00007FF6BCDFEB24]
	(No symbol) [0x00007FF6BCDFECB2]
	(No symbol) [0x00007FF6BCDEE17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-07-31 15:25:26,259:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-07-31 15:46:40,831:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-07-31 15:47:26,829:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-07-31 15:49:44,819:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-07-31 15:51:01,287:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-07-31 15:53:36,925:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-07-31 15:55:29,726:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-07-31 16:55:53,983:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=126.0.6478.183)
Stacktrace:
	GetHandleVerifier [0x00007FF72CF1EEB2+31554]
	(No symbol) [0x00007FF72CE97EE9]
	(No symbol) [0x00007FF72CD5872A]
	(No symbol) [0x00007FF72CD2D995]
	(No symbol) [0x00007FF72CDD44D7]
	(No symbol) [0x00007FF72CDEC051]
	(No symbol) [0x00007FF72CDCCDD3]
	(No symbol) [0x00007FF72CD9A33B]
	(No symbol) [0x00007FF72CD9AED1]
	GetHandleVerifier [0x00007FF72D228B2D+3217341]
	GetHandleVerifier [0x00007FF72D275AF3+3532675]
	GetHandleVerifier [0x00007FF72D26B0F0+3489152]
	GetHandleVerifier [0x00007FF72CFCE786+750614]
	(No symbol) [0x00007FF72CEA376F]
	(No symbol) [0x00007FF72CE9EB24]
	(No symbol) [0x00007FF72CE9ECB2]
	(No symbol) [0x00007FF72CE8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 106, in run
    claim = br.find_element(By.CSS_SELECTOR, 'a[data-item-id*="merchant"]').get_attribute('aria-label')
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1248, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=126.0.6478.183)
Stacktrace:
	GetHandleVerifier [0x00007FF72CF1EEB2+31554]
	(No symbol) [0x00007FF72CE97EE9]
	(No symbol) [0x00007FF72CD5872A]
	(No symbol) [0x00007FF72CD2D995]
	(No symbol) [0x00007FF72CDD44D7]
	(No symbol) [0x00007FF72CDEC051]
	(No symbol) [0x00007FF72CDCCDD3]
	(No symbol) [0x00007FF72CD9A33B]
	(No symbol) [0x00007FF72CD9AED1]
	GetHandleVerifier [0x00007FF72D228B2D+3217341]
	GetHandleVerifier [0x00007FF72D275AF3+3532675]
	GetHandleVerifier [0x00007FF72D26B0F0+3489152]
	GetHandleVerifier [0x00007FF72CFCE786+750614]
	(No symbol) [0x00007FF72CEA376F]
	(No symbol) [0x00007FF72CE9EB24]
	(No symbol) [0x00007FF72CE9ECB2]
	(No symbol) [0x00007FF72CE8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-07-31 16:58:05,327:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=126.0.6478.183)
Stacktrace:
	GetHandleVerifier [0x00007FF72CF1EEB2+31554]
	(No symbol) [0x00007FF72CE97EE9]
	(No symbol) [0x00007FF72CD5872A]
	(No symbol) [0x00007FF72CD2D995]
	(No symbol) [0x00007FF72CDD44D7]
	(No symbol) [0x00007FF72CDEC051]
	(No symbol) [0x00007FF72CDCCDD3]
	(No symbol) [0x00007FF72CD9A33B]
	(No symbol) [0x00007FF72CD9AED1]
	GetHandleVerifier [0x00007FF72D228B2D+3217341]
	GetHandleVerifier [0x00007FF72D275AF3+3532675]
	GetHandleVerifier [0x00007FF72D26B0F0+3489152]
	GetHandleVerifier [0x00007FF72CFCE786+750614]
	(No symbol) [0x00007FF72CEA376F]
	(No symbol) [0x00007FF72CE9EB24]
	(No symbol) [0x00007FF72CE9ECB2]
	(No symbol) [0x00007FF72CE8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 68, in run
    br.find_elements(By.CSS_SELECTOR, 'a[href*="https://www.google.com/maps/place/"]')
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1283, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=126.0.6478.183)
Stacktrace:
	GetHandleVerifier [0x00007FF72CF1EEB2+31554]
	(No symbol) [0x00007FF72CE97EE9]
	(No symbol) [0x00007FF72CD5872A]
	(No symbol) [0x00007FF72CD2D995]
	(No symbol) [0x00007FF72CDD44D7]
	(No symbol) [0x00007FF72CDEC051]
	(No symbol) [0x00007FF72CDCCDD3]
	(No symbol) [0x00007FF72CD9A33B]
	(No symbol) [0x00007FF72CD9AED1]
	GetHandleVerifier [0x00007FF72D228B2D+3217341]
	GetHandleVerifier [0x00007FF72D275AF3+3532675]
	GetHandleVerifier [0x00007FF72D26B0F0+3489152]
	GetHandleVerifier [0x00007FF72CFCE786+750614]
	(No symbol) [0x00007FF72CEA376F]
	(No symbol) [0x00007FF72CE9EB24]
	(No symbol) [0x00007FF72CE9ECB2]
	(No symbol) [0x00007FF72CE8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-07-31 17:00:55,106:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=126.0.6478.183)
Stacktrace:
	GetHandleVerifier [0x00007FF72CF1EEB2+31554]
	(No symbol) [0x00007FF72CE97EE9]
	(No symbol) [0x00007FF72CD5872A]
	(No symbol) [0x00007FF72CD2D995]
	(No symbol) [0x00007FF72CDD44D7]
	(No symbol) [0x00007FF72CDEC051]
	(No symbol) [0x00007FF72CDCCDD3]
	(No symbol) [0x00007FF72CD9A33B]
	(No symbol) [0x00007FF72CD9AED1]
	GetHandleVerifier [0x00007FF72D228B2D+3217341]
	GetHandleVerifier [0x00007FF72D275AF3+3532675]
	GetHandleVerifier [0x00007FF72D26B0F0+3489152]
	GetHandleVerifier [0x00007FF72CFCE786+750614]
	(No symbol) [0x00007FF72CEA376F]
	(No symbol) [0x00007FF72CE9EB24]
	(No symbol) [0x00007FF72CE9ECB2]
	(No symbol) [0x00007FF72CE8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 106, in run
    claim = br.find_element(By.CSS_SELECTOR, 'a[data-item-id*="merchant"]').get_attribute('aria-label')
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1248, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=126.0.6478.183)
Stacktrace:
	GetHandleVerifier [0x00007FF72CF1EEB2+31554]
	(No symbol) [0x00007FF72CE97EE9]
	(No symbol) [0x00007FF72CD5872A]
	(No symbol) [0x00007FF72CD2D995]
	(No symbol) [0x00007FF72CDD44D7]
	(No symbol) [0x00007FF72CDEC051]
	(No symbol) [0x00007FF72CDCCDD3]
	(No symbol) [0x00007FF72CD9A33B]
	(No symbol) [0x00007FF72CD9AED1]
	GetHandleVerifier [0x00007FF72D228B2D+3217341]
	GetHandleVerifier [0x00007FF72D275AF3+3532675]
	GetHandleVerifier [0x00007FF72D26B0F0+3489152]
	GetHandleVerifier [0x00007FF72CFCE786+750614]
	(No symbol) [0x00007FF72CEA376F]
	(No symbol) [0x00007FF72CE9EB24]
	(No symbol) [0x00007FF72CE9ECB2]
	(No symbol) [0x00007FF72CE8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-08-01 17:28:32,498:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 17:40:04,120:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 17:41:22,656:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 17:44:53,288:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 17:44:57,229:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 17:48:19,933:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 18:06:34,665:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 18:14:21,099:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 18:16:33,766:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 18:17:42,641:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 18:23:17,854:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 19:34:56,452:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 19:35:51,933:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 19:40:54,823:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 19:41:32,842:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 19:43:37,706:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 19:44:31,631:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 19:45:20,416:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 19:47:12,957:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 19:49:53,285:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 19:51:34,438:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-01 19:52:47,979:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 39, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-04 20:47:37,495:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF7AF01EEB2+31554]
	(No symbol) [0x00007FF7AEF97EE9]
	(No symbol) [0x00007FF7AEE5872A]
	(No symbol) [0x00007FF7AEE2D995]
	(No symbol) [0x00007FF7AEED44D7]
	(No symbol) [0x00007FF7AEEEC051]
	(No symbol) [0x00007FF7AEECCDD3]
	(No symbol) [0x00007FF7AEE9A33B]
	(No symbol) [0x00007FF7AEE9AED1]
	GetHandleVerifier [0x00007FF7AF328B2D+3217341]
	GetHandleVerifier [0x00007FF7AF375AF3+3532675]
	GetHandleVerifier [0x00007FF7AF36B0F0+3489152]
	GetHandleVerifier [0x00007FF7AF0CE786+750614]
	(No symbol) [0x00007FF7AEFA376F]
	(No symbol) [0x00007FF7AEF9EB24]
	(No symbol) [0x00007FF7AEF9ECB2]
	(No symbol) [0x00007FF7AEF8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 68, in run
    br.find_elements(By.CSS_SELECTOR, 'a[href*="https://www.google.com/maps/place/"]')
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1283, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF7AF01EEB2+31554]
	(No symbol) [0x00007FF7AEF97EE9]
	(No symbol) [0x00007FF7AEE5872A]
	(No symbol) [0x00007FF7AEE2D995]
	(No symbol) [0x00007FF7AEED44D7]
	(No symbol) [0x00007FF7AEEEC051]
	(No symbol) [0x00007FF7AEECCDD3]
	(No symbol) [0x00007FF7AEE9A33B]
	(No symbol) [0x00007FF7AEE9AED1]
	GetHandleVerifier [0x00007FF7AF328B2D+3217341]
	GetHandleVerifier [0x00007FF7AF375AF3+3532675]
	GetHandleVerifier [0x00007FF7AF36B0F0+3489152]
	GetHandleVerifier [0x00007FF7AF0CE786+750614]
	(No symbol) [0x00007FF7AEFA376F]
	(No symbol) [0x00007FF7AEF9EB24]
	(No symbol) [0x00007FF7AEF9ECB2]
	(No symbol) [0x00007FF7AEF8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-08-04 20:53:56,955:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF7AF01EEB2+31554]
	(No symbol) [0x00007FF7AEF97EE9]
	(No symbol) [0x00007FF7AEE5872A]
	(No symbol) [0x00007FF7AEE2D995]
	(No symbol) [0x00007FF7AEED44D7]
	(No symbol) [0x00007FF7AEEEC051]
	(No symbol) [0x00007FF7AEECCDD3]
	(No symbol) [0x00007FF7AEE9A33B]
	(No symbol) [0x00007FF7AEE9AED1]
	GetHandleVerifier [0x00007FF7AF328B2D+3217341]
	GetHandleVerifier [0x00007FF7AF375AF3+3532675]
	GetHandleVerifier [0x00007FF7AF36B0F0+3489152]
	GetHandleVerifier [0x00007FF7AF0CE786+750614]
	(No symbol) [0x00007FF7AEFA376F]
	(No symbol) [0x00007FF7AEF9EB24]
	(No symbol) [0x00007FF7AEF9ECB2]
	(No symbol) [0x00007FF7AEF8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 68, in run
    br.find_elements(By.CSS_SELECTOR, 'a[href*="https://www.google.com/maps/place/"]')
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1283, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF7AF01EEB2+31554]
	(No symbol) [0x00007FF7AEF97EE9]
	(No symbol) [0x00007FF7AEE5872A]
	(No symbol) [0x00007FF7AEE2D995]
	(No symbol) [0x00007FF7AEED44D7]
	(No symbol) [0x00007FF7AEEEC051]
	(No symbol) [0x00007FF7AEECCDD3]
	(No symbol) [0x00007FF7AEE9A33B]
	(No symbol) [0x00007FF7AEE9AED1]
	GetHandleVerifier [0x00007FF7AF328B2D+3217341]
	GetHandleVerifier [0x00007FF7AF375AF3+3532675]
	GetHandleVerifier [0x00007FF7AF36B0F0+3489152]
	GetHandleVerifier [0x00007FF7AF0CE786+750614]
	(No symbol) [0x00007FF7AEFA376F]
	(No symbol) [0x00007FF7AEF9EB24]
	(No symbol) [0x00007FF7AEF9ECB2]
	(No symbol) [0x00007FF7AEF8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-08-04 22:25:32,428:ERROR:gbm:'NoneType' object has no attribute 'get_attribute'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 106, in run
    claim = br.find_element(By.CSS_SELECTOR, 'a[data-item-id*="merchant"]').get_attribute('aria-label')
AttributeError: 'NoneType' object has no attribute 'get_attribute'
2024-08-04 23:03:28,906:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF7AF01EEB2+31554]
	(No symbol) [0x00007FF7AEF97EE9]
	(No symbol) [0x00007FF7AEE5872A]
	(No symbol) [0x00007FF7AEE2D995]
	(No symbol) [0x00007FF7AEED44D7]
	(No symbol) [0x00007FF7AEEEC051]
	(No symbol) [0x00007FF7AEECCDD3]
	(No symbol) [0x00007FF7AEE9A33B]
	(No symbol) [0x00007FF7AEE9AED1]
	GetHandleVerifier [0x00007FF7AF328B2D+3217341]
	GetHandleVerifier [0x00007FF7AF375AF3+3532675]
	GetHandleVerifier [0x00007FF7AF36B0F0+3489152]
	GetHandleVerifier [0x00007FF7AF0CE786+750614]
	(No symbol) [0x00007FF7AEFA376F]
	(No symbol) [0x00007FF7AEF9EB24]
	(No symbol) [0x00007FF7AEF9ECB2]
	(No symbol) [0x00007FF7AEF8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 62, in run
    br.find_elements(By.CSS_SELECTOR, 'a[href*="https://www.google.com/maps/place/"]')[-1]
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1283, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF7AF01EEB2+31554]
	(No symbol) [0x00007FF7AEF97EE9]
	(No symbol) [0x00007FF7AEE5872A]
	(No symbol) [0x00007FF7AEE2D995]
	(No symbol) [0x00007FF7AEED44D7]
	(No symbol) [0x00007FF7AEEEC051]
	(No symbol) [0x00007FF7AEECCDD3]
	(No symbol) [0x00007FF7AEE9A33B]
	(No symbol) [0x00007FF7AEE9AED1]
	GetHandleVerifier [0x00007FF7AF328B2D+3217341]
	GetHandleVerifier [0x00007FF7AF375AF3+3532675]
	GetHandleVerifier [0x00007FF7AF36B0F0+3489152]
	GetHandleVerifier [0x00007FF7AF0CE786+750614]
	(No symbol) [0x00007FF7AEFA376F]
	(No symbol) [0x00007FF7AEF9EB24]
	(No symbol) [0x00007FF7AEF9ECB2]
	(No symbol) [0x00007FF7AEF8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-08-04 23:14:52,103:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF7AF01EEB2+31554]
	(No symbol) [0x00007FF7AEF97EE9]
	(No symbol) [0x00007FF7AEE5872A]
	(No symbol) [0x00007FF7AEE2D995]
	(No symbol) [0x00007FF7AEED44D7]
	(No symbol) [0x00007FF7AEEEC051]
	(No symbol) [0x00007FF7AEECCDD3]
	(No symbol) [0x00007FF7AEE9A33B]
	(No symbol) [0x00007FF7AEE9AED1]
	GetHandleVerifier [0x00007FF7AF328B2D+3217341]
	GetHandleVerifier [0x00007FF7AF375AF3+3532675]
	GetHandleVerifier [0x00007FF7AF36B0F0+3489152]
	GetHandleVerifier [0x00007FF7AF0CE786+750614]
	(No symbol) [0x00007FF7AEFA376F]
	(No symbol) [0x00007FF7AEF9EB24]
	(No symbol) [0x00007FF7AEF9ECB2]
	(No symbol) [0x00007FF7AEF8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 62, in run
    br.find_elements(By.CSS_SELECTOR, 'a[href*="https://www.google.com/maps/place/"]')[-1]
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1283, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF7AF01EEB2+31554]
	(No symbol) [0x00007FF7AEF97EE9]
	(No symbol) [0x00007FF7AEE5872A]
	(No symbol) [0x00007FF7AEE2D995]
	(No symbol) [0x00007FF7AEED44D7]
	(No symbol) [0x00007FF7AEEEC051]
	(No symbol) [0x00007FF7AEECCDD3]
	(No symbol) [0x00007FF7AEE9A33B]
	(No symbol) [0x00007FF7AEE9AED1]
	GetHandleVerifier [0x00007FF7AF328B2D+3217341]
	GetHandleVerifier [0x00007FF7AF375AF3+3532675]
	GetHandleVerifier [0x00007FF7AF36B0F0+3489152]
	GetHandleVerifier [0x00007FF7AF0CE786+750614]
	(No symbol) [0x00007FF7AEFA376F]
	(No symbol) [0x00007FF7AEF9EB24]
	(No symbol) [0x00007FF7AEF9ECB2]
	(No symbol) [0x00007FF7AEF8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-08-04 23:22:40,919:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF7AF01EEB2+31554]
	(No symbol) [0x00007FF7AEF97EE9]
	(No symbol) [0x00007FF7AEE5872A]
	(No symbol) [0x00007FF7AEE2D995]
	(No symbol) [0x00007FF7AEED44D7]
	(No symbol) [0x00007FF7AEEEC051]
	(No symbol) [0x00007FF7AEECCDD3]
	(No symbol) [0x00007FF7AEE9A33B]
	(No symbol) [0x00007FF7AEE9AED1]
	GetHandleVerifier [0x00007FF7AF328B2D+3217341]
	GetHandleVerifier [0x00007FF7AF375AF3+3532675]
	GetHandleVerifier [0x00007FF7AF36B0F0+3489152]
	GetHandleVerifier [0x00007FF7AF0CE786+750614]
	(No symbol) [0x00007FF7AEFA376F]
	(No symbol) [0x00007FF7AEF9EB24]
	(No symbol) [0x00007FF7AEF9ECB2]
	(No symbol) [0x00007FF7AEF8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 68, in run
    br.find_elements(By.CSS_SELECTOR, 'a[href*="https://www.google.com/maps/place/"]')
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1283, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF7AF01EEB2+31554]
	(No symbol) [0x00007FF7AEF97EE9]
	(No symbol) [0x00007FF7AEE5872A]
	(No symbol) [0x00007FF7AEE2D995]
	(No symbol) [0x00007FF7AEED44D7]
	(No symbol) [0x00007FF7AEEEC051]
	(No symbol) [0x00007FF7AEECCDD3]
	(No symbol) [0x00007FF7AEE9A33B]
	(No symbol) [0x00007FF7AEE9AED1]
	GetHandleVerifier [0x00007FF7AF328B2D+3217341]
	GetHandleVerifier [0x00007FF7AF375AF3+3532675]
	GetHandleVerifier [0x00007FF7AF36B0F0+3489152]
	GetHandleVerifier [0x00007FF7AF0CE786+750614]
	(No symbol) [0x00007FF7AEFA376F]
	(No symbol) [0x00007FF7AEF9EB24]
	(No symbol) [0x00007FF7AEF9ECB2]
	(No symbol) [0x00007FF7AEF8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-08-04 23:28:40,619:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF7AF01EEB2+31554]
	(No symbol) [0x00007FF7AEF97EE9]
	(No symbol) [0x00007FF7AEE5872A]
	(No symbol) [0x00007FF7AEE2D995]
	(No symbol) [0x00007FF7AEED44D7]
	(No symbol) [0x00007FF7AEEEC051]
	(No symbol) [0x00007FF7AEECCDD3]
	(No symbol) [0x00007FF7AEE9A33B]
	(No symbol) [0x00007FF7AEE9AED1]
	GetHandleVerifier [0x00007FF7AF328B2D+3217341]
	GetHandleVerifier [0x00007FF7AF375AF3+3532675]
	GetHandleVerifier [0x00007FF7AF36B0F0+3489152]
	GetHandleVerifier [0x00007FF7AF0CE786+750614]
	(No symbol) [0x00007FF7AEFA376F]
	(No symbol) [0x00007FF7AEF9EB24]
	(No symbol) [0x00007FF7AEF9ECB2]
	(No symbol) [0x00007FF7AEF8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 76, in run
    for a in br.find_elements(By.CSS_SELECTOR, 'a[href*="https://www.google.com/maps/place/"]'):
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1283, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF7AF01EEB2+31554]
	(No symbol) [0x00007FF7AEF97EE9]
	(No symbol) [0x00007FF7AEE5872A]
	(No symbol) [0x00007FF7AEE2D995]
	(No symbol) [0x00007FF7AEED44D7]
	(No symbol) [0x00007FF7AEEEC051]
	(No symbol) [0x00007FF7AEECCDD3]
	(No symbol) [0x00007FF7AEE9A33B]
	(No symbol) [0x00007FF7AEE9AED1]
	GetHandleVerifier [0x00007FF7AF328B2D+3217341]
	GetHandleVerifier [0x00007FF7AF375AF3+3532675]
	GetHandleVerifier [0x00007FF7AF36B0F0+3489152]
	GetHandleVerifier [0x00007FF7AF0CE786+750614]
	(No symbol) [0x00007FF7AEFA376F]
	(No symbol) [0x00007FF7AEF9EB24]
	(No symbol) [0x00007FF7AEF9ECB2]
	(No symbol) [0x00007FF7AEF8E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-08-05 13:10:34,136:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF6CE5AEEB2+31554]
	(No symbol) [0x00007FF6CE527EE9]
	(No symbol) [0x00007FF6CE3E872A]
	(No symbol) [0x00007FF6CE3BD995]
	(No symbol) [0x00007FF6CE4644D7]
	(No symbol) [0x00007FF6CE47C051]
	(No symbol) [0x00007FF6CE45CDD3]
	(No symbol) [0x00007FF6CE42A33B]
	(No symbol) [0x00007FF6CE42AED1]
	GetHandleVerifier [0x00007FF6CE8B8B2D+3217341]
	GetHandleVerifier [0x00007FF6CE905AF3+3532675]
	GetHandleVerifier [0x00007FF6CE8FB0F0+3489152]
	GetHandleVerifier [0x00007FF6CE65E786+750614]
	(No symbol) [0x00007FF6CE53376F]
	(No symbol) [0x00007FF6CE52EB24]
	(No symbol) [0x00007FF6CE52ECB2]
	(No symbol) [0x00007FF6CE51E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 108, in run
    claim = br.find_element(By.CSS_SELECTOR, 'a[data-item-id*="merchant"]').get_attribute('aria-label')
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1248, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF6CE5AEEB2+31554]
	(No symbol) [0x00007FF6CE527EE9]
	(No symbol) [0x00007FF6CE3E872A]
	(No symbol) [0x00007FF6CE3BD995]
	(No symbol) [0x00007FF6CE4644D7]
	(No symbol) [0x00007FF6CE47C051]
	(No symbol) [0x00007FF6CE45CDD3]
	(No symbol) [0x00007FF6CE42A33B]
	(No symbol) [0x00007FF6CE42AED1]
	GetHandleVerifier [0x00007FF6CE8B8B2D+3217341]
	GetHandleVerifier [0x00007FF6CE905AF3+3532675]
	GetHandleVerifier [0x00007FF6CE8FB0F0+3489152]
	GetHandleVerifier [0x00007FF6CE65E786+750614]
	(No symbol) [0x00007FF6CE53376F]
	(No symbol) [0x00007FF6CE52EB24]
	(No symbol) [0x00007FF6CE52ECB2]
	(No symbol) [0x00007FF6CE51E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-08-05 13:16:10,265:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF6CE5AEEB2+31554]
	(No symbol) [0x00007FF6CE527EE9]
	(No symbol) [0x00007FF6CE3E872A]
	(No symbol) [0x00007FF6CE3BD995]
	(No symbol) [0x00007FF6CE4644D7]
	(No symbol) [0x00007FF6CE47C051]
	(No symbol) [0x00007FF6CE45CDD3]
	(No symbol) [0x00007FF6CE42A33B]
	(No symbol) [0x00007FF6CE42AED1]
	GetHandleVerifier [0x00007FF6CE8B8B2D+3217341]
	GetHandleVerifier [0x00007FF6CE905AF3+3532675]
	GetHandleVerifier [0x00007FF6CE8FB0F0+3489152]
	GetHandleVerifier [0x00007FF6CE65E786+750614]
	(No symbol) [0x00007FF6CE53376F]
	(No symbol) [0x00007FF6CE52EB24]
	(No symbol) [0x00007FF6CE52ECB2]
	(No symbol) [0x00007FF6CE51E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 64, in run
    br.find_elements(By.CSS_SELECTOR, 'a[href*="https://www.google.com/maps/place/"]')[-1]
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1283, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF6CE5AEEB2+31554]
	(No symbol) [0x00007FF6CE527EE9]
	(No symbol) [0x00007FF6CE3E872A]
	(No symbol) [0x00007FF6CE3BD995]
	(No symbol) [0x00007FF6CE4644D7]
	(No symbol) [0x00007FF6CE47C051]
	(No symbol) [0x00007FF6CE45CDD3]
	(No symbol) [0x00007FF6CE42A33B]
	(No symbol) [0x00007FF6CE42AED1]
	GetHandleVerifier [0x00007FF6CE8B8B2D+3217341]
	GetHandleVerifier [0x00007FF6CE905AF3+3532675]
	GetHandleVerifier [0x00007FF6CE8FB0F0+3489152]
	GetHandleVerifier [0x00007FF6CE65E786+750614]
	(No symbol) [0x00007FF6CE53376F]
	(No symbol) [0x00007FF6CE52EB24]
	(No symbol) [0x00007FF6CE52ECB2]
	(No symbol) [0x00007FF6CE51E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-08-05 13:44:44,418:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF6CE5AEEB2+31554]
	(No symbol) [0x00007FF6CE527EE9]
	(No symbol) [0x00007FF6CE3E872A]
	(No symbol) [0x00007FF6CE3BD995]
	(No symbol) [0x00007FF6CE4644D7]
	(No symbol) [0x00007FF6CE47C051]
	(No symbol) [0x00007FF6CE45CDD3]
	(No symbol) [0x00007FF6CE42A33B]
	(No symbol) [0x00007FF6CE42AED1]
	GetHandleVerifier [0x00007FF6CE8B8B2D+3217341]
	GetHandleVerifier [0x00007FF6CE905AF3+3532675]
	GetHandleVerifier [0x00007FF6CE8FB0F0+3489152]
	GetHandleVerifier [0x00007FF6CE65E786+750614]
	(No symbol) [0x00007FF6CE53376F]
	(No symbol) [0x00007FF6CE52EB24]
	(No symbol) [0x00007FF6CE52ECB2]
	(No symbol) [0x00007FF6CE51E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 78, in run
    for a in br.find_elements(By.CSS_SELECTOR, 'a[href*="https://www.google.com/maps/place/"]'):
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1283, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF6CE5AEEB2+31554]
	(No symbol) [0x00007FF6CE527EE9]
	(No symbol) [0x00007FF6CE3E872A]
	(No symbol) [0x00007FF6CE3BD995]
	(No symbol) [0x00007FF6CE4644D7]
	(No symbol) [0x00007FF6CE47C051]
	(No symbol) [0x00007FF6CE45CDD3]
	(No symbol) [0x00007FF6CE42A33B]
	(No symbol) [0x00007FF6CE42AED1]
	GetHandleVerifier [0x00007FF6CE8B8B2D+3217341]
	GetHandleVerifier [0x00007FF6CE905AF3+3532675]
	GetHandleVerifier [0x00007FF6CE8FB0F0+3489152]
	GetHandleVerifier [0x00007FF6CE65E786+750614]
	(No symbol) [0x00007FF6CE53376F]
	(No symbol) [0x00007FF6CE52EB24]
	(No symbol) [0x00007FF6CE52ECB2]
	(No symbol) [0x00007FF6CE51E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-08-07 11:42:56,525:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF73FADEEB2+31554]
	(No symbol) [0x00007FF73FA57EE9]
	(No symbol) [0x00007FF73F91872A]
	(No symbol) [0x00007FF73F8ED995]
	(No symbol) [0x00007FF73F9944D7]
	(No symbol) [0x00007FF73F9AC051]
	(No symbol) [0x00007FF73F98CDD3]
	(No symbol) [0x00007FF73F95A33B]
	(No symbol) [0x00007FF73F95AED1]
	GetHandleVerifier [0x00007FF73FDE8B2D+3217341]
	GetHandleVerifier [0x00007FF73FE35AF3+3532675]
	GetHandleVerifier [0x00007FF73FE2B0F0+3489152]
	GetHandleVerifier [0x00007FF73FB8E786+750614]
	(No symbol) [0x00007FF73FA6376F]
	(No symbol) [0x00007FF73FA5EB24]
	(No symbol) [0x00007FF73FA5ECB2]
	(No symbol) [0x00007FF73FA4E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 108, in run
    claim = br.find_element(By.CSS_SELECTOR, 'a[data-item-id*="merchant"]').get_attribute('aria-label')
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1248, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF73FADEEB2+31554]
	(No symbol) [0x00007FF73FA57EE9]
	(No symbol) [0x00007FF73F91872A]
	(No symbol) [0x00007FF73F8ED995]
	(No symbol) [0x00007FF73F9944D7]
	(No symbol) [0x00007FF73F9AC051]
	(No symbol) [0x00007FF73F98CDD3]
	(No symbol) [0x00007FF73F95A33B]
	(No symbol) [0x00007FF73F95AED1]
	GetHandleVerifier [0x00007FF73FDE8B2D+3217341]
	GetHandleVerifier [0x00007FF73FE35AF3+3532675]
	GetHandleVerifier [0x00007FF73FE2B0F0+3489152]
	GetHandleVerifier [0x00007FF73FB8E786+750614]
	(No symbol) [0x00007FF73FA6376F]
	(No symbol) [0x00007FF73FA5EB24]
	(No symbol) [0x00007FF73FA5ECB2]
	(No symbol) [0x00007FF73FA4E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-08-07 13:53:02,111:ERROR:gbm:Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF73FADEEB2+31554]
	(No symbol) [0x00007FF73FA57EE9]
	(No symbol) [0x00007FF73F91872A]
	(No symbol) [0x00007FF73F8ED995]
	(No symbol) [0x00007FF73F9944D7]
	(No symbol) [0x00007FF73F9AC051]
	(No symbol) [0x00007FF73F98CDD3]
	(No symbol) [0x00007FF73F95A33B]
	(No symbol) [0x00007FF73F95AED1]
	GetHandleVerifier [0x00007FF73FDE8B2D+3217341]
	GetHandleVerifier [0x00007FF73FE35AF3+3532675]
	GetHandleVerifier [0x00007FF73FE2B0F0+3489152]
	GetHandleVerifier [0x00007FF73FB8E786+750614]
	(No symbol) [0x00007FF73FA6376F]
	(No symbol) [0x00007FF73FA5EB24]
	(No symbol) [0x00007FF73FA5ECB2]
	(No symbol) [0x00007FF73FA4E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 108, in run
    claim = br.find_element(By.CSS_SELECTOR, 'a[data-item-id*="merchant"]').get_attribute('aria-label')
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1248, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF73FADEEB2+31554]
	(No symbol) [0x00007FF73FA57EE9]
	(No symbol) [0x00007FF73F91872A]
	(No symbol) [0x00007FF73F8ED995]
	(No symbol) [0x00007FF73F9944D7]
	(No symbol) [0x00007FF73F9AC051]
	(No symbol) [0x00007FF73F98CDD3]
	(No symbol) [0x00007FF73F95A33B]
	(No symbol) [0x00007FF73F95AED1]
	GetHandleVerifier [0x00007FF73FDE8B2D+3217341]
	GetHandleVerifier [0x00007FF73FE35AF3+3532675]
	GetHandleVerifier [0x00007FF73FE2B0F0+3489152]
	GetHandleVerifier [0x00007FF73FB8E786+750614]
	(No symbol) [0x00007FF73FA6376F]
	(No symbol) [0x00007FF73FA5EB24]
	(No symbol) [0x00007FF73FA5ECB2]
	(No symbol) [0x00007FF73FA4E17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-08-07 15:55:39,881:INFO:gbm.tasks:Adding ['asbestos in london']
2024-08-07 16:09:53,937:ERROR:gbm:Message: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF63AE7EEB2+31554]
	(No symbol) [0x00007FF63ADF7EE9]
	(No symbol) [0x00007FF63ACB872A]
	(No symbol) [0x00007FF63ACA0FDD]
	(No symbol) [0x00007FF63ACA0CE0]
	(No symbol) [0x00007FF63AC9FC9B]
	(No symbol) [0x00007FF63ACC630D]
	(No symbol) [0x00007FF63AD4CCD5]
	(No symbol) [0x00007FF63AD2CDD3]
	(No symbol) [0x00007FF63ACFA33B]
	(No symbol) [0x00007FF63ACFAED1]
	GetHandleVerifier [0x00007FF63B188B2D+3217341]
	GetHandleVerifier [0x00007FF63B1D5AF3+3532675]
	GetHandleVerifier [0x00007FF63B1CB0F0+3489152]
	GetHandleVerifier [0x00007FF63AF2E786+750614]
	(No symbol) [0x00007FF63AE0376F]
	(No symbol) [0x00007FF63ADFEB24]
	(No symbol) [0x00007FF63ADFECB2]
	(No symbol) [0x00007FF63ADEE17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\gbm_extractor\gbm\utils.py", line 105, in run
    br.get(url)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 437, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SONIKA SHARMA\anaconda3\envs\myenv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF63AE7EEB2+31554]
	(No symbol) [0x00007FF63ADF7EE9]
	(No symbol) [0x00007FF63ACB872A]
	(No symbol) [0x00007FF63ACA0FDD]
	(No symbol) [0x00007FF63ACA0CE0]
	(No symbol) [0x00007FF63AC9FC9B]
	(No symbol) [0x00007FF63ACC630D]
	(No symbol) [0x00007FF63AD4CCD5]
	(No symbol) [0x00007FF63AD2CDD3]
	(No symbol) [0x00007FF63ACFA33B]
	(No symbol) [0x00007FF63ACFAED1]
	GetHandleVerifier [0x00007FF63B188B2D+3217341]
	GetHandleVerifier [0x00007FF63B1D5AF3+3532675]
	GetHandleVerifier [0x00007FF63B1CB0F0+3489152]
	GetHandleVerifier [0x00007FF63AF2E786+750614]
	(No symbol) [0x00007FF63AE0376F]
	(No symbol) [0x00007FF63ADFEB24]
	(No symbol) [0x00007FF63ADFECB2]
	(No symbol) [0x00007FF63ADEE17F]
	BaseThreadInitThunk [0x00007FFCD50E257D+29]
	RtlUserThreadStart [0x00007FFCD640AF28+40]

2024-08-08 15:29:37,039:INFO:gbm.tasks:Adding ['asbestos in london']
2024-08-08 15:43:14,244:INFO:gbm.tasks:Adding ['asbestos in london']
2024-08-08 15:53:45,344:INFO:gbm.tasks:Adding ['asbestos in london']
2024-08-21 13:35:03,515:INFO:gbm.tasks:Adding ['pest control in sydney']
2024-08-21 13:39:47,898:INFO:gbm.tasks:Adding ['pest control in sydney']
2024-08-21 13:39:53,665:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\utils.py", line 62, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-21 13:42:16,818:INFO:gbm.tasks:Adding ['pest control in melbourn']
2024-08-21 13:42:19,558:ERROR:gbm:WebDriver.__init__() got an unexpected keyword argument 'executable_path'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\utils.py", line 62, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\webdriver.py", line 25, in __init__
    super().__init__(executable_path='C:/Users/SONIKA SHARMA/Desktop/gbm_extractor/gbm/chromedriver.exe', chrome_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
2024-08-21 13:53:06,274:INFO:gbm.tasks:Adding ['pest control in melbourn']
2024-08-21 13:53:08,627:ERROR:gbm:name 'Service' is not defined
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\utils.py", line 62, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\webdriver.py", line 25, in __init__
    service= Service(ChromeDriverManager().install())
             ^^^^^^^
NameError: name 'Service' is not defined
2024-08-21 13:53:10,706:INFO:gbm.tasks:Adding ['pest control in sydney']
2024-08-21 13:53:13,221:ERROR:gbm:name 'Service' is not defined
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\utils.py", line 62, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\webdriver.py", line 25, in __init__
    service= Service(ChromeDriverManager().install())
             ^^^^^^^
NameError: name 'Service' is not defined
2024-08-21 13:55:50,239:INFO:gbm.tasks:Adding ['pest control in sydney']
2024-08-21 13:55:52,991:ERROR:gbm:name 'Service' is not defined
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\utils.py", line 62, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\webdriver.py", line 25, in __init__
    service = Service(ChromeDriverManager().install())
              ^^^^^^^
NameError: name 'Service' is not defined
2024-08-21 13:58:10,361:INFO:gbm.tasks:Adding ['pest control in sydney']
2024-08-21 13:58:13,242:ERROR:gbm:name 'ChromeDriverManager' is not defined
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\utils.py", line 62, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\webdriver.py", line 26, in __init__
    service = Service(ChromeDriverManager().install())
                      ^^^^^^^^^^^^^^^^^^^
NameError: name 'ChromeDriverManager' is not defined
2024-08-21 14:03:22,510:INFO:gbm.tasks:Adding ['pest control in sydney']
2024-08-21 14:03:27,157:ERROR:gbm:'super' object has no attribute '_init_'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\utils.py", line 62, in run
    br = WebDriver()
         ^^^^^^^^^^^
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\webdriver.py", line 29, in __init__
    super()._init_(service=service, options=options)
    ^^^^^^^^^^^^^^
AttributeError: 'super' object has no attribute '_init_'. Did you mean: '__init__'?
2024-08-21 14:05:02,784:INFO:gbm.tasks:Adding ['pest control in sydney']
2024-08-21 17:12:30,685:INFO:gbm.tasks:Adding ['asbestos in london']
2024-08-21 17:14:16,576:ERROR:gbm:'WebDriver' object has no attribute 'find_element_by_xpath'
Traceback (most recent call last):
  File "C:\Users\SONIKA SHARMA\Desktop\djnago-project\gbm\utils.py", line 154, in run
    name = br.find_element_by_xpath('//*[@id="QA0Szd"]/div/div/div[1]/div[2]/div/div[1]/div/div/div[2]/div/div[1]/div[1]/h1').text
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WebDriver' object has no attribute 'find_element_by_xpath'. Did you mean: 'find_element_or_none'?
